import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navbar";
import Footer from "./ui/footer";
import CreateButton from "./ui/create-button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "warég",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CreateButton />
        <Navbar />
        <div style={{ overflowX: "hidden" }}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
